#define CONSTANT 1
#define INT 2
#define STRING 3
#define ASSIGN 4
#define END_INSTRUCTION 5
#define PRINT 6
#define READ 7
#define IF 8
#define ELSE 9
#define START_BRACKETS 10
#define END_BRACKETS 11
#define START_SPECIAL_BRACKETS 12
#define END_SPECIAL_BRACKETS 13
#define PLUS 14
#define MINUS 15
#define STAR 16
#define LESS_OR_EQUAL 17
#define GREATER_OR_EQUAL 18
#define LESS 19
#define GREATER 20
#define EQUAL 21
#define NON_EQUAL 22
#define FOR 24
#define RANGE 25
#define COLON 26
#define QUOTE 27
#define IDENTIFIER 28
#define NEXT 29